export type ColumnKind = "pk" | "fk" | "pk-fk";

export type Column = {
  name: string;
  type: string;
  kind?: ColumnKind;
  nullable?: boolean;
  note?: string;
};

export type TableGroup = "dim" | "fact";

export type TableSpec = {
  id: string;
  name: string;
  group: TableGroup;
  domain:
    | "capacity"
    | "kpi"
    | "delivery"
    | "pipeline"
    | "ai"
    | "reference"
    | "rules";
  description: string;
  columns: Column[];
};

export type Relation = {
  from: string;
  to: string;
  label: string;
};

export const TABLES: TableSpec[] = [
  // ---------- Capacity domain ----------
  {
    id: "cp2_dim_team_member",
    name: "cp2_dim_team_member",
    group: "dim",
    domain: "capacity",
    description: "Editorial team roster — identity, role, baseline capacity.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "full_name", type: "string" },
      { name: "email", type: "string" },
      { name: "role_default", type: "enum", note: "SE|ED|WR|AD|PM" },
      { name: "default_monthly_capacity_articles", type: "float" },
      { name: "start_month", type: "date" },
      { name: "end_month", type: "date", nullable: true },
      { name: "is_active", type: "bool" },
      { name: "notes", type: "text" },
    ],
  },
  {
    id: "cp2_dim_pod",
    name: "cp2_dim_pod",
    group: "dim",
    domain: "capacity",
    description: "Pods — the unit that owns clients and members for a month.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "pod_number", type: "int" },
      { name: "display_name", type: "string" },
      { name: "active_from", type: "date" },
      { name: "active_to", type: "date", nullable: true },
      { name: "notes", type: "text" },
    ],
  },
  {
    id: "cp2_dim_client",
    name: "cp2_dim_client",
    group: "dim",
    domain: "reference",
    description:
      "Client master — SOW contract, cadence, milestone dates, staffing, cumulative totals. Feeds every card on Editorial Clients.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "client_id_fk", type: "int", kind: "fk", note: "clients.id" },
      { name: "name", type: "string" },
      { name: "domain", type: "string", nullable: true },
      {
        name: "status",
        type: "enum",
        note: "ACTIVE|COMPLETED|CANCELLED|SOON_TO_BE_ACTIVE|INACTIVE",
      },
      { name: "growth_pod", type: "string", nullable: true },
      { name: "editorial_pod", type: "string", nullable: true },
      { name: "engagement_tier_id", type: "int", kind: "fk", nullable: true },
      { name: "project_type", type: "string", nullable: true },
      { name: "cadence", type: "enum", note: "quarterly|monthly|custom" },
      { name: "cadence_q1", type: "int", nullable: true },
      { name: "cadence_q2", type: "int", nullable: true },
      { name: "cadence_q3", type: "int", nullable: true },
      { name: "cadence_q4", type: "int", nullable: true },
      { name: "term_months", type: "int", nullable: true },
      { name: "sow_articles_total", type: "int" },
      { name: "sow_articles_per_month", type: "int" },
      { name: "word_count_min", type: "int", nullable: true },
      { name: "word_count_max", type: "int", nullable: true },
      { name: "sow_link", type: "text", nullable: true },
      { name: "contract_start", type: "date" },
      { name: "contract_end", type: "date" },
      { name: "consulting_ko_date", type: "date", nullable: true },
      { name: "editorial_ko_date", type: "date", nullable: true },
      { name: "first_cb_approved_date", type: "date", nullable: true },
      { name: "first_article_delivered_date", type: "date", nullable: true },
      { name: "first_feedback_date", type: "date", nullable: true },
      { name: "first_article_published_date", type: "date", nullable: true },
      { name: "managing_director", type: "string", nullable: true },
      { name: "account_director", type: "string", nullable: true },
      { name: "account_manager", type: "string", nullable: true },
      { name: "jr_am", type: "string", nullable: true },
      { name: "cs_team", type: "text", nullable: true },
      { name: "articles_delivered", type: "int", note: "cumulative" },
      { name: "articles_invoiced", type: "int", note: "cumulative" },
      { name: "articles_paid", type: "int", note: "cumulative" },
      { name: "is_active_in_cp2", type: "bool" },
      { name: "comments", type: "text", nullable: true },
    ],
  },
  {
    id: "cp2_dim_engagement_tier",
    name: "cp2_dim_engagement_tier",
    group: "dim",
    domain: "reference",
    description: "Engagement tiers — pricing and service-level labels.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "name", type: "string", note: "Premium|Standard|Custom" },
      { name: "description", type: "text" },
    ],
  },
  {
    id: "cp2_dim_month",
    name: "cp2_dim_month",
    group: "dim",
    domain: "reference",
    description: "Month calendar — the planning grain for capacity and KPIs.",
    columns: [
      { name: "month_key", type: "string", kind: "pk", note: "YYYY-MM" },
      { name: "year", type: "int" },
      { name: "month_num", type: "int" },
      { name: "quarter", type: "string" },
      { name: "is_current", type: "bool" },
      { name: "is_forecast", type: "bool" },
    ],
  },
  {
    id: "cp2_dim_week",
    name: "cp2_dim_week",
    group: "dim",
    domain: "reference",
    description: "ISO weeks — the measurement grain for actuals and goals.",
    columns: [
      { name: "week_key", type: "string", kind: "pk", note: "YYYY-Www" },
      { name: "month_key", type: "string", kind: "fk" },
      { name: "week_start", type: "date" },
      { name: "week_end", type: "date" },
      { name: "iso_year", type: "int" },
      { name: "iso_week", type: "int" },
    ],
  },
  {
    id: "cp2_dim_delivery_template",
    name: "cp2_dim_delivery_template",
    group: "dim",
    domain: "reference",
    description:
      "Cadence templates by SOW size — used by the pacing calculator on the Client Delivery table.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "sow_size", type: "int", note: "e.g. 120, 180, 240 articles" },
      { name: "month_number", type: "int", note: "1..term_months" },
      { name: "delivery_target", type: "int" },
      { name: "delivery_cumulative", type: "int" },
      { name: "invoicing_target", type: "int" },
      { name: "invoicing_cumulative", type: "int" },
    ],
  },
  {
    id: "cp2_fact_pod_membership",
    name: "cp2_fact_pod_membership",
    group: "fact",
    domain: "capacity",
    description: "Per-month assignment of a member to a pod with a capacity share.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "month_key", type: "string", kind: "fk" },
      { name: "pod_id", type: "int", kind: "fk" },
      { name: "team_member_id", type: "int", kind: "fk" },
      { name: "role_in_pod", type: "enum", note: "SE|ED|WR|AD|PM" },
      { name: "capacity_share", type: "float", note: "0.0 – 1.0" },
      { name: "notes", type: "text" },
    ],
  },
  {
    id: "cp2_fact_client_allocation",
    name: "cp2_fact_client_allocation",
    group: "fact",
    domain: "capacity",
    description: "Per-month client → pod allocation with projected article count.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "month_key", type: "string", kind: "fk" },
      { name: "pod_id", type: "int", kind: "fk" },
      { name: "client_id", type: "int", kind: "fk" },
      { name: "projected_articles", type: "int" },
      { name: "projected_source", type: "enum", note: "manual|operating_model|sow" },
      { name: "projected_articles_manual", type: "int", nullable: true },
      { name: "notes", type: "text" },
    ],
  },
  {
    id: "cp2_fact_member_leave",
    name: "cp2_fact_member_leave",
    group: "fact",
    domain: "capacity",
    description: "PTO / leave per member for a month, as a fraction of working time.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "team_member_id", type: "int", kind: "fk" },
      { name: "month_key", type: "string", kind: "fk" },
      { name: "leave_share", type: "float", note: "0.0 – 1.0 of month" },
      { name: "reason", type: "string", note: "PTO|Parental|Sick|Other" },
      { name: "notes", type: "text" },
    ],
  },
  {
    id: "cp2_fact_capacity_override",
    name: "cp2_fact_capacity_override",
    group: "fact",
    domain: "capacity",
    description: "Manual corrections to effective capacity at member or pod level.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "month_key", type: "string", kind: "fk" },
      { name: "team_member_id", type: "int", kind: "fk", nullable: true },
      { name: "pod_id", type: "int", kind: "fk", nullable: true },
      { name: "delta_articles", type: "int", note: "signed" },
      { name: "reason", type: "text" },
      { name: "created_by", type: "string" },
      { name: "created_at", type: "timestamp" },
    ],
  },
  {
    id: "cp2_fact_actuals_weekly",
    name: "cp2_fact_actuals_weekly",
    group: "fact",
    domain: "delivery",
    description:
      "Weekly CB + AD goals vs delivered per client × pod × week. Expanded to mirror every column of goals_vs_delivery so the Weekly Goals section on Editorial Clients renders from a single source.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "week_key", type: "string", kind: "fk" },
      { name: "month_year_key", type: "string", note: "YYYY-MM denorm" },
      { name: "week_number", type: "int" },
      { name: "week_date", type: "date", nullable: true },
      { name: "pod_id", type: "int", kind: "fk" },
      { name: "client_id", type: "int", kind: "fk" },
      { name: "growth_team_pod", type: "string", nullable: true },
      { name: "editorial_team_pod", type: "string", nullable: true },
      { name: "client_type", type: "string", nullable: true },
      { name: "content_type", type: "string", nullable: true },
      { name: "ratios", type: "string", nullable: true, note: "e.g. 2:1" },

      { name: "delivered_articles", type: "int", note: "AD delivered this week" },
      { name: "goal_articles", type: "int", note: "AD weekly slice of monthly goal" },

      { name: "cb_delivered_today", type: "int", nullable: true },
      { name: "cb_projection", type: "int", nullable: true },
      { name: "cb_delivered_to_date", type: "int", nullable: true },
      { name: "cb_monthly_goal", type: "int", nullable: true },
      { name: "cb_pct_of_goal", type: "string", nullable: true },
      { name: "cb_comments", type: "text", nullable: true },

      { name: "ad_revisions", type: "int", nullable: true },
      { name: "ad_delivered_today", type: "int", nullable: true },
      { name: "ad_projection", type: "int", nullable: true },
      { name: "ad_cb_backlog", type: "int", nullable: true },
      { name: "ad_delivered_to_date", type: "int", nullable: true },
      { name: "ad_monthly_goal", type: "int", nullable: true },
      { name: "ad_pct_of_goal", type: "string", nullable: true },
      { name: "ad_comments", type: "text", nullable: true },

      { name: "ingested_at", type: "timestamp" },
    ],
  },

  // ---------- KPI domain ----------
  {
    id: "cp2_dim_kpi_metric",
    name: "cp2_dim_kpi_metric",
    group: "dim",
    domain: "kpi",
    description: "Catalog of every KPI — display name, unit, target, direction, formula.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "metric_key", type: "string", note: "e.g. internal_quality" },
      { name: "display_name", type: "string" },
      { name: "unit", type: "enum", note: "percent|score|days|count" },
      { name: "target_value", type: "float" },
      {
        name: "direction",
        type: "enum",
        note: "higher_is_better|lower_is_better|band",
      },
      { name: "formula", type: "text", note: "human-readable definition" },
      { name: "applies_to_roles", type: "string", note: "CSV: SE,ED,WR" },
    ],
  },
  {
    id: "cp2_fact_kpi_score",
    name: "cp2_fact_kpi_score",
    group: "fact",
    domain: "kpi",
    description:
      "Monthly KPI score. Grain is (team_member, metric, month, client?). A null client_id means an aggregate score across all clients; a non-null client_id powers the per-client breakdown cards.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "month_key", type: "string", kind: "fk" },
      { name: "team_member_id", type: "int", kind: "fk" },
      { name: "metric_id", type: "int", kind: "fk" },
      { name: "client_id", type: "int", kind: "fk", nullable: true },
      { name: "score", type: "float", nullable: true },
      { name: "target_snapshot", type: "float", note: "target at time of entry" },
      { name: "source", type: "enum", note: "manual|notion|ai_scan|capacity" },
      { name: "entered_by", type: "string", nullable: true },
      { name: "entered_at", type: "timestamp" },
      { name: "notes", type: "text" },
    ],
  },

  // ---------- Article + AI ----------
  {
    id: "cp2_fact_article",
    name: "cp2_fact_article",
    group: "fact",
    domain: "kpi",
    description:
      "Article-level workflow tracking — powers Revision Rate, Turnaround Time, Second Reviews, and per-article AI scans.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "notion_case_id", type: "string", note: "FK to notion_articles.case_id" },
      { name: "client_id", type: "int", kind: "fk" },
      { name: "pod_id", type: "int", kind: "fk", nullable: true },
      { name: "writer_id", type: "int", kind: "fk", nullable: true },
      { name: "editor_id", type: "int", kind: "fk", nullable: true },
      { name: "sr_editor_id", type: "int", kind: "fk", nullable: true },
      { name: "month_key", type: "string", kind: "fk", note: "bucket for KPI rollups" },
      { name: "title", type: "string", nullable: true },
      { name: "content_type", type: "string", nullable: true },
      { name: "article_status", type: "string", nullable: true },
      { name: "cb_approved_date", type: "date", nullable: true },
      { name: "delivered_date", type: "date", nullable: true },
      { name: "published_date", type: "date", nullable: true },
      { name: "turnaround_days", type: "int", nullable: true, note: "persisted" },
      { name: "revision_count", type: "int" },
      { name: "had_second_review", type: "bool" },
      { name: "published_url", type: "text", nullable: true },
      { name: "notion_url", type: "text", nullable: true },
      {
        name: "status",
        type: "enum",
        note: "drafting|review|delivered|published|killed",
      },
    ],
  },
  {
    id: "cp2_fact_ai_scan",
    name: "cp2_fact_ai_scan",
    group: "fact",
    domain: "ai",
    description:
      "AI-detection scans per article — powers the AI Compliance tab (summary, breakdowns, flagged list, rewrites list).",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "article_id", type: "int", kind: "fk", nullable: true },
      { name: "client_id", type: "int", kind: "fk" },
      { name: "pod_id", type: "int", kind: "fk", nullable: true },
      { name: "month_key", type: "string", kind: "fk" },
      { name: "topic_title", type: "string" },
      { name: "topic_content", type: "text", nullable: true },
      { name: "article_link", type: "text", nullable: true },
      { name: "writer_name", type: "string", nullable: true, note: "denorm" },
      { name: "editor_name", type: "string", nullable: true, note: "denorm" },
      { name: "scanned_at", type: "timestamp" },
      { name: "date_processed", type: "date", nullable: true },
      { name: "surfer_v1_score", type: "float", nullable: true },
      { name: "surfer_v2_score", type: "float", nullable: true },
      {
        name: "recommendation",
        type: "enum",
        note: "FULL_PASS|PARTIAL_PASS|REVIEW_REWRITE",
      },
      { name: "is_rewrite", type: "bool" },
      { name: "is_flagged", type: "bool" },
      { name: "manual_review_notes", type: "text", nullable: true },
      { name: "action", type: "string", nullable: true },
      { name: "notes", type: "text", nullable: true },
    ],
  },
  {
    id: "cp2_fact_surfer_api_usage",
    name: "cp2_fact_surfer_api_usage",
    group: "fact",
    domain: "ai",
    description:
      "Monthly Surfer API spend per pod, plus auditioning writers and rewrite counts.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "year_month_key", type: "string", kind: "fk" },
      { name: "start_date", type: "date", nullable: true },
      { name: "end_date", type: "date", nullable: true },
      { name: "pod_1", type: "int" },
      { name: "pod_2", type: "int" },
      { name: "pod_3", type: "int" },
      { name: "pod_4", type: "int" },
      { name: "pod_5", type: "int" },
      { name: "auditioning_writers", type: "int" },
      { name: "rewrites", type: "int" },
      { name: "total_spent", type: "int" },
      { name: "remaining_calls", type: "int", nullable: true },
    ],
  },

  // ---------- Delivery (invoicing + operating-model + pipeline) ----------
  {
    id: "cp2_fact_delivery_monthly",
    name: "cp2_fact_delivery_monthly",
    group: "fact",
    domain: "delivery",
    description:
      "Monthly delivered / invoiced / paid per client, plus monthly SOW target and CB counts. Feeds Delivery Overview, Client Delivery Matrix, and Variance.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "month_key", type: "string", kind: "fk" },
      { name: "client_id", type: "int", kind: "fk" },
      { name: "articles_sow_target", type: "int" },
      { name: "articles_delivered", type: "int" },
      { name: "articles_invoiced", type: "int" },
      { name: "articles_paid", type: "int" },
      { name: "articles_projected", type: "int", nullable: true },
      { name: "is_actual", type: "bool" },
      { name: "variance", type: "int", note: "delivered - sow_target" },
      { name: "content_briefs_delivered", type: "int" },
      { name: "content_briefs_goal", type: "int" },
      { name: "cumulative_delivered", type: "int" },
      { name: "cumulative_invoiced", type: "int" },
      { name: "source", type: "enum", note: "manual|operating_model|sheet_import" },
      { name: "notes", type: "text", nullable: true },
    ],
  },
  {
    id: "cp2_fact_production_history",
    name: "cp2_fact_production_history",
    group: "fact",
    domain: "delivery",
    description:
      "Projected vs actual articles per client per month — preserves the operating-model forecast alongside actualized deliveries so the Production Trend chart can plot both series.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "client_id", type: "int", kind: "fk" },
      { name: "month_key", type: "string", kind: "fk" },
      { name: "articles_actual", type: "int", nullable: true },
      { name: "articles_projected", type: "int", nullable: true },
      { name: "is_actual", type: "bool" },
      { name: "source", type: "string", note: "e.g. operating_model, manual" },
    ],
  },
  {
    id: "cp2_fact_pipeline_snapshot",
    name: "cp2_fact_pipeline_snapshot",
    group: "fact",
    domain: "pipeline",
    description:
      "All-time cumulative pipeline per client — feeds the Cumulative Pipeline section. Denormalizes status / pod / type for display without joins.",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "snapshot_date", type: "date" },
      { name: "client_id", type: "int", kind: "fk" },
      { name: "status", type: "string", nullable: true },
      { name: "account_team_pod", type: "string", nullable: true },
      { name: "client_type", type: "string", nullable: true },
      { name: "content_type", type: "string", nullable: true },
      { name: "topics_submitted", type: "int" },
      { name: "topics_approved", type: "int" },
      { name: "topics_pct_approved", type: "string", nullable: true },
      { name: "cbs_submitted", type: "int" },
      { name: "cbs_approved", type: "int" },
      { name: "cbs_pct_approved", type: "string", nullable: true },
      { name: "articles_sent", type: "int" },
      { name: "articles_approved", type: "int" },
      { name: "articles_difference", type: "int" },
      { name: "articles_pct_approved", type: "string", nullable: true },
      { name: "articles_delivered", type: "int" },
      { name: "articles_published", type: "int" },
      { name: "published_pct_live", type: "string", nullable: true },
      { name: "articles_killed", type: "int" },
      { name: "last_update", type: "date", nullable: true },
      { name: "comments", type: "text", nullable: true },
    ],
  },

  // ---------- Rules + assumptions ----------
  {
    id: "cp2_dim_engagement_rule",
    name: "cp2_dim_engagement_rule",
    group: "dim",
    domain: "rules",
    description:
      '"10 Commandments" rule catalog — drives compliance scoring and pacing alerts.',
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "rule_number", type: "int" },
      { name: "area", type: "string", note: "workflow|quality|delivery" },
      { name: "rule_name", type: "string" },
      { name: "description", type: "text" },
      { name: "owner", type: "string", nullable: true },
      { name: "timing", type: "string", nullable: true },
      { name: "consequences", type: "text", nullable: true },
    ],
  },
  {
    id: "cp2_dim_model_assumption",
    name: "cp2_dim_model_assumption",
    group: "dim",
    domain: "rules",
    description:
      "Key-value business assumptions (ramp-up periods, capacity targets, thresholds).",
    columns: [
      { name: "id", type: "int", kind: "pk" },
      { name: "category", type: "string" },
      { name: "key", type: "string" },
      { name: "value", type: "string" },
      { name: "description", type: "text", nullable: true },
    ],
  },
];

export const RELATIONS: Relation[] = [
  // capacity
  { from: "cp2_dim_team_member", to: "cp2_fact_pod_membership", label: "assigned to" },
  { from: "cp2_dim_pod", to: "cp2_fact_pod_membership", label: "has members" },
  { from: "cp2_dim_month", to: "cp2_fact_pod_membership", label: "for month" },
  { from: "cp2_dim_pod", to: "cp2_fact_client_allocation", label: "owns clients" },
  { from: "cp2_dim_client", to: "cp2_fact_client_allocation", label: "allocated to pod" },
  { from: "cp2_dim_month", to: "cp2_fact_client_allocation", label: "for month" },
  { from: "cp2_dim_team_member", to: "cp2_fact_member_leave", label: "takes leave" },
  { from: "cp2_dim_month", to: "cp2_fact_member_leave", label: "affects month" },
  { from: "cp2_dim_team_member", to: "cp2_fact_capacity_override", label: "override on" },
  { from: "cp2_dim_pod", to: "cp2_fact_capacity_override", label: "override on" },
  { from: "cp2_dim_month", to: "cp2_fact_capacity_override", label: "for month" },

  // delivery
  { from: "cp2_dim_pod", to: "cp2_fact_actuals_weekly", label: "delivers" },
  { from: "cp2_dim_client", to: "cp2_fact_actuals_weekly", label: "receives" },
  { from: "cp2_dim_week", to: "cp2_fact_actuals_weekly", label: "in week" },
  { from: "cp2_dim_month", to: "cp2_fact_delivery_monthly", label: "in month" },
  { from: "cp2_dim_client", to: "cp2_fact_delivery_monthly", label: "for client" },
  { from: "cp2_dim_client", to: "cp2_fact_production_history", label: "for client" },
  { from: "cp2_dim_month", to: "cp2_fact_production_history", label: "in month" },

  // kpi
  { from: "cp2_dim_kpi_metric", to: "cp2_fact_kpi_score", label: "measures" },
  { from: "cp2_dim_team_member", to: "cp2_fact_kpi_score", label: "scored for" },
  { from: "cp2_dim_month", to: "cp2_fact_kpi_score", label: "for month" },
  { from: "cp2_dim_client", to: "cp2_fact_kpi_score", label: "per client" },

  // article + AI
  { from: "cp2_dim_client", to: "cp2_fact_article", label: "article for" },
  { from: "cp2_dim_pod", to: "cp2_fact_article", label: "produced by pod" },
  { from: "cp2_dim_team_member", to: "cp2_fact_article", label: "writer/editor" },
  { from: "cp2_dim_month", to: "cp2_fact_article", label: "delivered in" },
  { from: "cp2_fact_article", to: "cp2_fact_ai_scan", label: "scanned" },
  { from: "cp2_dim_client", to: "cp2_fact_ai_scan", label: "article for" },
  { from: "cp2_dim_month", to: "cp2_fact_ai_scan", label: "in month" },
  { from: "cp2_dim_month", to: "cp2_fact_surfer_api_usage", label: "in month" },

  // pipeline
  { from: "cp2_dim_client", to: "cp2_fact_pipeline_snapshot", label: "pipeline for" },

  // reference
  { from: "cp2_dim_month", to: "cp2_dim_week", label: "contains" },
  { from: "cp2_dim_engagement_tier", to: "cp2_dim_client", label: "tier of" },
];

// ---------------------------------------------------------------------------
// KPI glossary — every dashboard metric mapped to ERD column(s) + formula
// ---------------------------------------------------------------------------

export type KpiMapping = {
  metric_key: string;
  display_name: string;
  dashboard: "team-kpis" | "editorial-clients";
  unit: string;
  target: string;
  direction: "higher_is_better" | "lower_is_better" | "band";
  currentSource: string;
  erdTable: string;
  erdColumns: string[];
  formula: string;
  notes?: string;
};

export const KPI_GLOSSARY: KpiMapping[] = [
  // Team KPIs dashboard
  {
    metric_key: "internal_quality",
    display_name: "Internal Quality",
    dashboard: "team-kpis",
    unit: "score 0–100",
    target: "≥85",
    direction: "higher_is_better",
    currentSource: "Monthly KPI Scores sheet",
    erdTable: "cp2_fact_kpi_score",
    erdColumns: ["score", "target_snapshot", "metric_id=internal_quality"],
    formula: "Manual monthly score entered by SE, per editor (client_id optional).",
  },
  {
    metric_key: "external_quality",
    display_name: "External Quality",
    dashboard: "team-kpis",
    unit: "score 0–100",
    target: "≥85",
    direction: "higher_is_better",
    currentSource: "Monthly KPI Scores sheet",
    erdTable: "cp2_fact_kpi_score",
    erdColumns: ["score", "metric_id=external_quality"],
    formula: "Client satisfaction score from post-delivery feedback.",
  },
  {
    metric_key: "mentorship",
    display_name: "Mentorship",
    dashboard: "team-kpis",
    unit: "score 0–100",
    target: "≥80",
    direction: "higher_is_better",
    currentSource: "Monthly KPI Scores sheet",
    erdTable: "cp2_fact_kpi_score",
    erdColumns: ["score", "metric_id=mentorship"],
    formula: "Effectiveness of mentorship from Editor feedback (SE only).",
  },
  {
    metric_key: "feedback_adoption",
    display_name: "Feedback Adoption",
    dashboard: "team-kpis",
    unit: "score 0–100",
    target: "≥80",
    direction: "higher_is_better",
    currentSource: "Monthly KPI Scores sheet",
    erdTable: "cp2_fact_kpi_score",
    erdColumns: ["score", "metric_id=feedback_adoption"],
    formula: "Rate of feedback incorporation into subsequent articles (ED only).",
  },
  {
    metric_key: "revision_rate",
    display_name: "Revision Rate",
    dashboard: "team-kpis",
    unit: "percent",
    target: "≤15%",
    direction: "lower_is_better",
    currentSource: "Notion Database",
    erdTable: "cp2_fact_article",
    erdColumns: ["revision_count", "status", "writer_id", "editor_id"],
    formula:
      "articles_with_revision_count>0 / articles_delivered per month × 100, aggregated to member via writer_id/editor_id.",
  },
  {
    metric_key: "turnaround_time",
    display_name: "Turnaround Time",
    dashboard: "team-kpis",
    unit: "days",
    target: "≤14",
    direction: "lower_is_better",
    currentSource: "Notion Database",
    erdTable: "cp2_fact_article",
    erdColumns: ["cb_approved_date", "delivered_date", "turnaround_days"],
    formula: "avg(delivered_date - cb_approved_date) over articles in the month.",
  },
  {
    metric_key: "second_reviews",
    display_name: "Second Reviews",
    dashboard: "team-kpis",
    unit: "count / month",
    target: "≥5",
    direction: "higher_is_better",
    currentSource: "Notion Database",
    erdTable: "cp2_fact_article",
    erdColumns: ["had_second_review", "sr_editor_id"],
    formula: "count(articles where had_second_review = true) grouped by sr_editor, month.",
  },
  {
    metric_key: "ai_compliance",
    display_name: "AI Compliance",
    dashboard: "team-kpis",
    unit: "percent",
    target: "≥95%",
    direction: "higher_is_better",
    currentSource: "Writer AI Monitoring 2.0 sheet",
    erdTable: "cp2_fact_ai_scan",
    erdColumns: ["recommendation", "is_flagged"],
    formula: "count(recommendation = FULL_PASS) / count(is_rewrite=false) per month × 100.",
  },
  {
    metric_key: "capacity_utilization",
    display_name: "Capacity Utilization",
    dashboard: "team-kpis",
    unit: "percent",
    target: "80–85% (band)",
    direction: "band",
    currentSource: "ET CP 2026 capacity_projections",
    erdTable: "cp2_v_pod_monthly (view)",
    erdColumns: ["projected_use", "total_capacity"],
    formula:
      "projected_use / total_capacity × 100; view joins pod_membership + client_allocation + member_leave + capacity_override.",
  },
  {
    metric_key: "surfer_api_spend",
    display_name: "Surfer API Spend (monthly)",
    dashboard: "team-kpis",
    unit: "calls",
    target: "within plan",
    direction: "band",
    currentSource: "AI Monitoring — Surfer Usage sheet",
    erdTable: "cp2_fact_surfer_api_usage",
    erdColumns: ["pod_1..pod_5", "auditioning_writers", "rewrites", "total_spent", "remaining_calls"],
    formula: "Per-pod monthly totals plus auditioning + rewrite calls. remaining_calls < 100 flags the card red.",
  },
  {
    metric_key: "ai_flagged",
    display_name: "AI Flagged Articles",
    dashboard: "team-kpis",
    unit: "count",
    target: "n/a",
    direction: "band",
    currentSource: "Writer AI Monitoring 2.0 sheet",
    erdTable: "cp2_fact_ai_scan",
    erdColumns: ["is_flagged", "topic_title", "recommendation", "action", "date_processed"],
    formula: "Raw list of scans with is_flagged=true, ordered by date_processed desc.",
  },

  // Editorial Clients dashboard
  {
    metric_key: "articles_delivered_monthly",
    display_name: "Articles Delivered (monthly)",
    dashboard: "editorial-clients",
    unit: "count",
    target: "= articles_sow_target",
    direction: "band",
    currentSource: "Delivered vs Invoiced v2",
    erdTable: "cp2_fact_delivery_monthly",
    erdColumns: ["articles_delivered", "articles_sow_target"],
    formula:
      "Monthly sum per client; compared to articles_sow_target and cumulative_delivered / sow_articles_total × 100.",
  },
  {
    metric_key: "articles_invoiced_monthly",
    display_name: "Articles Invoiced (monthly)",
    dashboard: "editorial-clients",
    unit: "count",
    target: "≈ delivered",
    direction: "band",
    currentSource: "Delivered vs Invoiced v2",
    erdTable: "cp2_fact_delivery_monthly",
    erdColumns: ["articles_invoiced", "variance"],
    formula: "Monthly sum; variance = delivered - sow_target.",
  },
  {
    metric_key: "articles_paid_monthly",
    display_name: "Articles Paid (monthly)",
    dashboard: "editorial-clients",
    unit: "count",
    target: "= invoiced",
    direction: "higher_is_better",
    currentSource: "Delivered vs Invoiced v2",
    erdTable: "cp2_fact_delivery_monthly",
    erdColumns: ["articles_paid"],
    formula: "Monthly sum per client.",
  },
  {
    metric_key: "content_briefs_monthly",
    display_name: "Content Briefs (delivered / goal)",
    dashboard: "editorial-clients",
    unit: "count",
    target: "= content_briefs_goal",
    direction: "higher_is_better",
    currentSource: "Delivered vs Invoiced v2 + Goals vs Delivery",
    erdTable: "cp2_fact_delivery_monthly",
    erdColumns: ["content_briefs_delivered", "content_briefs_goal"],
    formula: "Monthly CB delivery vs goal; feeds the CB section of Client Delivery Matrix.",
  },
  {
    metric_key: "production_trend",
    display_name: "Production Trend (actual vs projected)",
    dashboard: "editorial-clients",
    unit: "count / month",
    target: "n/a",
    direction: "band",
    currentSource: "Editorial Operating Model",
    erdTable: "cp2_fact_production_history",
    erdColumns: ["articles_actual", "articles_projected", "is_actual"],
    formula: "Two series over time; is_actual = true rows plot the actual series, else the projected series.",
  },
  {
    metric_key: "goals_weekly_cb",
    display_name: "Weekly CB Delivery",
    dashboard: "editorial-clients",
    unit: "count / week",
    target: "meet monthly CB goal",
    direction: "higher_is_better",
    currentSource: "Master Tracker Goals vs Delivery",
    erdTable: "cp2_fact_actuals_weekly",
    erdColumns: [
      "cb_delivered_today",
      "cb_delivered_to_date",
      "cb_monthly_goal",
      "cb_pct_of_goal",
      "cb_projection",
    ],
    formula: "Weekly CB row per (client, week) rolled up to month for display.",
  },
  {
    metric_key: "goals_weekly_ad",
    display_name: "Weekly Article Delivery",
    dashboard: "editorial-clients",
    unit: "count / week",
    target: "meet monthly AD goal",
    direction: "higher_is_better",
    currentSource: "Master Tracker Goals vs Delivery",
    erdTable: "cp2_fact_actuals_weekly",
    erdColumns: [
      "ad_delivered_today",
      "ad_delivered_to_date",
      "ad_monthly_goal",
      "ad_pct_of_goal",
      "ad_revisions",
      "ad_cb_backlog",
    ],
    formula: "Weekly AD row per (client, week); revisions and CB backlog shown inline.",
  },
  {
    metric_key: "cumulative_pipeline",
    display_name: "Cumulative Pipeline",
    dashboard: "editorial-clients",
    unit: "count",
    target: "monotonically increasing",
    direction: "higher_is_better",
    currentSource: "Master Tracker Cumulative",
    erdTable: "cp2_fact_pipeline_snapshot",
    erdColumns: [
      "topics_submitted",
      "cbs_approved",
      "articles_sent",
      "articles_approved",
      "articles_published",
      "articles_killed",
    ],
    formula:
      "Latest snapshot per client drives the per-client funnel; snapshots stored daily/weekly for trend lines.",
  },
  {
    metric_key: "pacing",
    display_name: "Pacing vs Template",
    dashboard: "editorial-clients",
    unit: "percent delta",
    target: "within ±10% of template",
    direction: "band",
    currentSource: "Delivery Schedules sheet",
    erdTable: "cp2_dim_delivery_template + cp2_fact_delivery_monthly",
    erdColumns: [
      "template.delivery_cumulative",
      "sum(delivery_monthly.articles_delivered) as actual_cum",
      "client.contract_start",
    ],
    formula:
      "months_elapsed = now - contract_start; expected = template[sow_size, months_elapsed].delivery_cumulative; delta = (actual - expected) / expected × 100.",
  },
  {
    metric_key: "time_to_milestones",
    display_name: "Time-to Milestones (8 deltas)",
    dashboard: "editorial-clients",
    unit: "days",
    target: "n/a",
    direction: "band",
    currentSource: "Editorial SOW overview",
    erdTable: "cp2_dim_client",
    erdColumns: [
      "consulting_ko_date",
      "editorial_ko_date",
      "first_cb_approved_date",
      "first_article_delivered_date",
      "first_feedback_date",
      "first_article_published_date",
    ],
    formula:
      "Each of the 8 waterfall rows is `(milestone_b − milestone_a)` in days over the client cohort.",
  },
  {
    metric_key: "client_timeline",
    display_name: "Client Engagement Timeline",
    dashboard: "editorial-clients",
    unit: "date range",
    target: "n/a",
    direction: "band",
    currentSource: "Editorial SOW overview",
    erdTable: "cp2_dim_client",
    erdColumns: [
      "contract_start",
      "contract_end",
      "term_months",
      "cadence",
      "cadence_q1",
      "cadence_q2",
      "cadence_q3",
      "cadence_q4",
      "sow_articles_total",
    ],
    formula: "Pure dim lookup — no aggregation. Per-client bar with colored pod and cadence sub-bars.",
  },
  {
    metric_key: "contract_detail",
    display_name: "Contract & Timeline Detail",
    dashboard: "editorial-clients",
    unit: "mixed",
    target: "n/a",
    direction: "band",
    currentSource: "Editorial SOW overview",
    erdTable: "cp2_dim_client",
    erdColumns: [
      "name",
      "status",
      "editorial_pod",
      "growth_pod",
      "contract_start",
      "contract_end",
      "term_months",
      "sow_articles_total",
      "sow_link",
      "word_count_min",
      "word_count_max",
      "consulting_ko_date",
      "editorial_ko_date",
      "first_cb_approved_date",
      "first_article_delivered_date",
      "first_feedback_date",
      "first_article_published_date",
    ],
    formula: "Direct column reads from cp2_dim_client; sort + filter client-side.",
  },
];
