// Representative mock rows per cp2_* table.
// Purpose: let reviewers SEE what each table is supposed to hold before any
// migration is written. Shapes match the ERD in `_erd.ts`.

export type MockRow = Record<string, string | number | boolean | null>;

export const TABLE_MOCK_ROWS: Record<string, MockRow[]> = {
  cp2_dim_team_member: [
    {
      id: 101,
      full_name: "Nina Derossi",
      email: "nina@graphitehq.com",
      role_default: "SE",
      default_monthly_capacity_articles: 12,
      start_month: "2024-09-01",
      end_month: null,
      is_active: true,
      notes: "",
    },
    {
      id: 102,
      full_name: "Robert Trampe",
      email: "robert@graphitehq.com",
      role_default: "ED",
      default_monthly_capacity_articles: 10,
      start_month: "2024-09-01",
      end_month: null,
      is_active: true,
      notes: "",
    },
    {
      id: 103,
      full_name: "Jimmy Bowes",
      email: "jimmy@graphitehq.com",
      role_default: "ED",
      default_monthly_capacity_articles: 8,
      start_month: "2025-02-01",
      end_month: null,
      is_active: true,
      notes: "split across Pod 1 and Pod 2",
    },
  ],
  cp2_dim_pod: [
    { id: 1, pod_number: 1, display_name: "Nina's Pod", active_from: "2024-09-01", active_to: null, notes: "" },
    { id: 2, pod_number: 2, display_name: "Kennedy's Pod", active_from: "2024-09-01", active_to: null, notes: "" },
    { id: 3, pod_number: 3, display_name: "Meredith's Pod", active_from: "2025-03-01", active_to: null, notes: "scaled for AI-sector clients" },
  ],
  cp2_dim_client: [
    {
      id: 1,
      client_id_fk: 42,
      engagement_tier_id: 1,
      cadence: "monthly",
      sow_articles_total: 300,
      sow_articles_per_month: 25,
      contract_start: "2025-01-01",
      contract_end: "2026-12-31",
      first_cb_approved_date: "2025-01-18",
      first_article_delivered_date: "2025-02-02",
      first_article_published_date: "2025-02-10",
      is_active_in_cp2: true,
    },
    {
      id: 2,
      client_id_fk: 58,
      engagement_tier_id: 2,
      cadence: "quarterly",
      sow_articles_total: 60,
      sow_articles_per_month: 5,
      contract_start: "2025-06-01",
      contract_end: "2026-06-30",
      first_cb_approved_date: "2025-06-14",
      first_article_delivered_date: "2025-06-28",
      first_article_published_date: null,
      is_active_in_cp2: true,
    },
  ],
  cp2_dim_engagement_tier: [
    { id: 1, name: "Premium", description: "Full CB + article + senior review" },
    { id: 2, name: "Standard", description: "Article + editorial review" },
    { id: 3, name: "Custom", description: "Bespoke SOW — see notes" },
  ],
  cp2_dim_month: [
    { month_key: "2026-02", year: 2026, month_num: 2, quarter: "Q1", is_current: false, is_forecast: false },
    { month_key: "2026-03", year: 2026, month_num: 3, quarter: "Q1", is_current: false, is_forecast: false },
    { month_key: "2026-04", year: 2026, month_num: 4, quarter: "Q2", is_current: true, is_forecast: false },
    { month_key: "2026-05", year: 2026, month_num: 5, quarter: "Q2", is_current: false, is_forecast: true },
  ],
  cp2_dim_week: [
    { week_key: "2026-W14", month_key: "2026-04", week_start: "2026-03-30", week_end: "2026-04-05", iso_year: 2026, iso_week: 14 },
    { week_key: "2026-W15", month_key: "2026-04", week_start: "2026-04-06", week_end: "2026-04-12", iso_year: 2026, iso_week: 15 },
    { week_key: "2026-W16", month_key: "2026-04", week_start: "2026-04-13", week_end: "2026-04-19", iso_year: 2026, iso_week: 16 },
  ],
  cp2_dim_kpi_metric: [
    { id: 1, metric_key: "internal_quality", display_name: "Internal Quality", unit: "score", target_value: 85, direction: "higher_is_better", formula: "Manual score by SE", applies_to_roles: "SE,ED" },
    { id: 2, metric_key: "external_quality", display_name: "External Quality", unit: "score", target_value: 85, direction: "higher_is_better", formula: "Client satisfaction score", applies_to_roles: "SE,ED" },
    { id: 3, metric_key: "revision_rate", display_name: "Revision Rate", unit: "percent", target_value: 15, direction: "lower_is_better", formula: "revisions / delivered × 100", applies_to_roles: "SE,ED,WR" },
    { id: 4, metric_key: "turnaround_time", display_name: "Turnaround Time", unit: "days", target_value: 14, direction: "lower_is_better", formula: "avg(delivered - cb_approved)", applies_to_roles: "SE,ED" },
    { id: 5, metric_key: "second_reviews", display_name: "Second Reviews", unit: "count", target_value: 5, direction: "higher_is_better", formula: "count(had_second_review)", applies_to_roles: "SE" },
    { id: 6, metric_key: "ai_compliance", display_name: "AI Compliance", unit: "percent", target_value: 95, direction: "higher_is_better", formula: "FULL_PASS / total × 100", applies_to_roles: "SE,ED,WR" },
    { id: 7, metric_key: "mentorship", display_name: "Mentorship", unit: "score", target_value: 80, direction: "higher_is_better", formula: "Mentorship effectiveness", applies_to_roles: "SE" },
    { id: 8, metric_key: "feedback_adoption", display_name: "Feedback Adoption", unit: "score", target_value: 80, direction: "higher_is_better", formula: "Rate of feedback incorporation", applies_to_roles: "ED" },
    { id: 9, metric_key: "capacity_utilization", display_name: "Capacity Utilization", unit: "percent", target_value: 82, direction: "band", formula: "projected / capacity × 100", applies_to_roles: "SE,ED,WR" },
  ],
  cp2_fact_pod_membership: [
    { id: 501, month_key: "2026-04", pod_id: 1, team_member_id: 101, role_in_pod: "SE", capacity_share: 0.3, notes: "split" },
    { id: 502, month_key: "2026-04", pod_id: 1, team_member_id: 102, role_in_pod: "ED", capacity_share: 1.0, notes: "" },
    { id: 503, month_key: "2026-04", pod_id: 1, team_member_id: 103, role_in_pod: "ED", capacity_share: 0.5, notes: "split with Pod 2" },
  ],
  cp2_fact_client_allocation: [
    { id: 701, month_key: "2026-04", pod_id: 1, client_id: 1, projected_articles: 25, projected_source: "sow", projected_articles_manual: null, notes: "" },
    { id: 702, month_key: "2026-04", pod_id: 1, client_id: 2, projected_articles: 25, projected_source: "operating_model", projected_articles_manual: null, notes: "" },
    { id: 703, month_key: "2026-04", pod_id: 1, client_id: 3, projected_articles: 8, projected_source: "manual", projected_articles_manual: 8, notes: "manual override per SE" },
  ],
  cp2_fact_member_leave: [
    { id: 901, team_member_id: 202, month_key: "2026-04", leave_share: 0.25, reason: "PTO", notes: "week 16" },
  ],
  cp2_fact_capacity_override: [
    { id: 1101, month_key: "2026-04", team_member_id: 203, pod_id: null, delta_articles: -2, reason: "onboarding ramp", created_by: "nina@graphitehq.com", created_at: "2026-03-28 11:14:02" },
  ],
  cp2_fact_actuals_weekly: [
    { id: 1301, week_key: "2026-W14", pod_id: 1, client_id: 1, delivered_articles: 6, goal_articles: 6, ingested_at: "2026-04-06 09:00:00" },
    { id: 1302, week_key: "2026-W15", pod_id: 1, client_id: 1, delivered_articles: 5, goal_articles: 6, ingested_at: "2026-04-13 09:00:00" },
  ],
  cp2_fact_kpi_score: [
    { id: 1501, month_key: "2026-04", team_member_id: 102, metric_id: 1, score: 87, target_snapshot: 85, source: "manual", entered_by: "nina@graphitehq.com", entered_at: "2026-04-30 17:02:11", notes: "" },
    { id: 1502, month_key: "2026-04", team_member_id: 102, metric_id: 3, score: 12, target_snapshot: 15, source: "notion", entered_by: null, entered_at: "2026-05-01 02:00:00", notes: "computed nightly" },
    { id: 1503, month_key: "2026-04", team_member_id: 102, metric_id: 6, score: 97, target_snapshot: 95, source: "ai_scan", entered_by: null, entered_at: "2026-05-01 02:00:00", notes: "from Writer AI 2.0" },
  ],
  cp2_fact_article: [
    {
      id: 2001,
      notion_case_id: "CASE-00123",
      client_id: 1,
      pod_id: 1,
      writer_id: 301,
      editor_id: 102,
      sr_editor_id: 101,
      month_key: "2026-04",
      cb_approved_date: "2026-04-02",
      delivered_date: "2026-04-11",
      published_date: "2026-04-15",
      turnaround_days: 9,
      revision_count: 0,
      had_second_review: true,
      status: "published",
    },
    {
      id: 2002,
      notion_case_id: "CASE-00124",
      client_id: 1,
      pod_id: 1,
      writer_id: 302,
      editor_id: 103,
      sr_editor_id: null,
      month_key: "2026-04",
      cb_approved_date: "2026-04-05",
      delivered_date: "2026-04-22",
      published_date: null,
      turnaround_days: 17,
      revision_count: 2,
      had_second_review: false,
      status: "delivered",
    },
  ],
  cp2_fact_ai_scan: [
    { id: 3001, article_id: 2001, client_id: 1, pod_id: 1, month_key: "2026-04", scanned_at: "2026-04-11 14:22", surfer_v1_score: 3.1, surfer_v2_score: 2.8, recommendation: "FULL_PASS", is_rewrite: false, is_flagged: false, notes: "" },
    { id: 3002, article_id: 2002, client_id: 1, pod_id: 1, month_key: "2026-04", scanned_at: "2026-04-22 10:02", surfer_v1_score: 18.4, surfer_v2_score: 14.6, recommendation: "PARTIAL_PASS", is_rewrite: false, is_flagged: true, notes: "reviewed by ED" },
  ],
  cp2_fact_delivery_monthly: [
    { id: 4001, month_key: "2026-04", client_id: 1, articles_delivered: 24, articles_invoiced: 25, variance: -1, cumulative_delivered: 312, cumulative_invoiced: 310, source: "operating_model" },
    { id: 4002, month_key: "2026-04", client_id: 2, articles_delivered: 5, articles_invoiced: 5, variance: 0, cumulative_delivered: 50, cumulative_invoiced: 50, source: "operating_model" },
  ],
  cp2_fact_pipeline_snapshot: [
    { id: 5001, snapshot_date: "2026-04-15", client_id: 1, topics_submitted: 420, cbs_approved: 410, articles_delivered: 398, articles_published: 360, articles_killed: 10 },
    { id: 5002, snapshot_date: "2026-04-15", client_id: 2, topics_submitted: 85, cbs_approved: 80, articles_delivered: 75, articles_published: 55, articles_killed: 2 },
  ],
};
