// Representative mock rows per cp2_* table.
// Purpose: let reviewers SEE what each table is supposed to hold before any
// migration is written. Shapes match the ERD in `_erd.ts`.

export type MockRow = Record<string, string | number | boolean | null>;

export const TABLE_MOCK_ROWS: Record<string, MockRow[]> = {
  cp2_dim_team_member: [
    {
      id: 101,
      full_name: "Nina Derossi",
      email: "nina@graphitehq.com",
      role_default: "SE",
      default_monthly_capacity_articles: 12,
      start_month: "2024-09-01",
      end_month: null,
      is_active: true,
      notes: "",
    },
    {
      id: 102,
      full_name: "Robert Trampe",
      email: "robert@graphitehq.com",
      role_default: "ED",
      default_monthly_capacity_articles: 10,
      start_month: "2024-09-01",
      end_month: null,
      is_active: true,
      notes: "",
    },
    {
      id: 103,
      full_name: "Jimmy Bowes",
      email: "jimmy@graphitehq.com",
      role_default: "ED",
      default_monthly_capacity_articles: 8,
      start_month: "2025-02-01",
      end_month: null,
      is_active: true,
      notes: "split across Pod 1 and Pod 2",
    },
  ],
  cp2_dim_pod: [
    { id: 1, pod_number: 1, display_name: "Nina's Pod", active_from: "2024-09-01", active_to: null, notes: "" },
    { id: 2, pod_number: 2, display_name: "Kennedy's Pod", active_from: "2024-09-01", active_to: null, notes: "" },
    { id: 3, pod_number: 3, display_name: "Meredith's Pod", active_from: "2025-03-01", active_to: null, notes: "AI-sector clients" },
  ],
  cp2_dim_client: [
    {
      id: 1,
      client_id_fk: 42,
      name: "College of BP",
      domain: "collegeofbp.com",
      status: "ACTIVE",
      growth_pod: "growth-1",
      editorial_pod: "editorial-1",
      engagement_tier_id: 1,
      project_type: "content-program",
      cadence: "monthly",
      cadence_q1: 60,
      cadence_q2: 60,
      cadence_q3: 60,
      cadence_q4: 60,
      term_months: 12,
      sow_articles_total: 300,
      sow_articles_per_month: 25,
      word_count_min: 1500,
      word_count_max: 2500,
      sow_link: "https://docs.google.com/document/d/abc123",
      contract_start: "2025-01-01",
      contract_end: "2026-12-31",
      consulting_ko_date: "2024-12-10",
      editorial_ko_date: "2024-12-20",
      first_cb_approved_date: "2025-01-18",
      first_article_delivered_date: "2025-02-02",
      first_feedback_date: "2025-02-08",
      first_article_published_date: "2025-02-10",
      managing_director: "Sarah Chen",
      account_director: "Marcus Wang",
      account_manager: "Priya Shah",
      jr_am: "Luis Ortiz",
      cs_team: "Emma Park, Dan Levitt",
      articles_delivered: 312,
      articles_invoiced: 310,
      articles_paid: 295,
      is_active_in_cp2: true,
      comments: "High-touch account, expanding to SEO in Q3",
    },
    {
      id: 2,
      client_id_fk: 58,
      name: "Harvard",
      domain: "harvard.edu",
      status: "ACTIVE",
      growth_pod: "growth-2",
      editorial_pod: "editorial-1",
      engagement_tier_id: 2,
      project_type: "thought-leadership",
      cadence: "quarterly",
      cadence_q1: 15,
      cadence_q2: 15,
      cadence_q3: 15,
      cadence_q4: 15,
      term_months: 12,
      sow_articles_total: 60,
      sow_articles_per_month: 5,
      word_count_min: 2000,
      word_count_max: 3000,
      sow_link: "https://docs.google.com/document/d/def456",
      contract_start: "2025-06-01",
      contract_end: "2026-06-30",
      consulting_ko_date: "2025-05-15",
      editorial_ko_date: "2025-05-28",
      first_cb_approved_date: "2025-06-14",
      first_article_delivered_date: "2025-06-28",
      first_feedback_date: "2025-07-05",
      first_article_published_date: null,
      managing_director: "Sarah Chen",
      account_director: "Jonathan Park",
      account_manager: "Fatima Rahman",
      jr_am: null,
      cs_team: "Dan Levitt",
      articles_delivered: 50,
      articles_invoiced: 50,
      articles_paid: 45,
      is_active_in_cp2: true,
      comments: "",
    },
  ],
  cp2_dim_engagement_tier: [
    { id: 1, name: "Premium", description: "Full CB + article + senior review" },
    { id: 2, name: "Standard", description: "Article + editorial review" },
    { id: 3, name: "Custom", description: "Bespoke SOW — see notes" },
  ],
  cp2_dim_month: [
    { month_key: "2026-02", year: 2026, month_num: 2, quarter: "Q1", is_current: false, is_forecast: false },
    { month_key: "2026-03", year: 2026, month_num: 3, quarter: "Q1", is_current: false, is_forecast: false },
    { month_key: "2026-04", year: 2026, month_num: 4, quarter: "Q2", is_current: true, is_forecast: false },
    { month_key: "2026-05", year: 2026, month_num: 5, quarter: "Q2", is_current: false, is_forecast: true },
  ],
  cp2_dim_week: [
    { week_key: "2026-W14", month_key: "2026-04", week_start: "2026-03-30", week_end: "2026-04-05", iso_year: 2026, iso_week: 14 },
    { week_key: "2026-W15", month_key: "2026-04", week_start: "2026-04-06", week_end: "2026-04-12", iso_year: 2026, iso_week: 15 },
    { week_key: "2026-W16", month_key: "2026-04", week_start: "2026-04-13", week_end: "2026-04-19", iso_year: 2026, iso_week: 16 },
  ],
  cp2_dim_delivery_template: [
    { id: 1, sow_size: 300, month_number: 1, delivery_target: 20, delivery_cumulative: 20, invoicing_target: 25, invoicing_cumulative: 25 },
    { id: 2, sow_size: 300, month_number: 2, delivery_target: 25, delivery_cumulative: 45, invoicing_target: 25, invoicing_cumulative: 50 },
    { id: 3, sow_size: 300, month_number: 3, delivery_target: 25, delivery_cumulative: 70, invoicing_target: 25, invoicing_cumulative: 75 },
    { id: 4, sow_size: 60, month_number: 1, delivery_target: 3, delivery_cumulative: 3, invoicing_target: 5, invoicing_cumulative: 5 },
    { id: 5, sow_size: 60, month_number: 2, delivery_target: 5, delivery_cumulative: 8, invoicing_target: 5, invoicing_cumulative: 10 },
  ],
  cp2_dim_kpi_metric: [
    { id: 1, metric_key: "internal_quality", display_name: "Internal Quality", unit: "score", target_value: 85, direction: "higher_is_better", formula: "Manual score by SE", applies_to_roles: "SE,ED" },
    { id: 2, metric_key: "external_quality", display_name: "External Quality", unit: "score", target_value: 85, direction: "higher_is_better", formula: "Client satisfaction score", applies_to_roles: "SE,ED" },
    { id: 3, metric_key: "revision_rate", display_name: "Revision Rate", unit: "percent", target_value: 15, direction: "lower_is_better", formula: "revisions / delivered × 100", applies_to_roles: "SE,ED,WR" },
    { id: 4, metric_key: "turnaround_time", display_name: "Turnaround Time", unit: "days", target_value: 14, direction: "lower_is_better", formula: "avg(delivered − cb_approved)", applies_to_roles: "SE,ED" },
    { id: 5, metric_key: "second_reviews", display_name: "Second Reviews", unit: "count", target_value: 5, direction: "higher_is_better", formula: "count(had_second_review)", applies_to_roles: "SE" },
    { id: 6, metric_key: "ai_compliance", display_name: "AI Compliance", unit: "percent", target_value: 95, direction: "higher_is_better", formula: "FULL_PASS / total × 100", applies_to_roles: "SE,ED,WR" },
    { id: 7, metric_key: "mentorship", display_name: "Mentorship", unit: "score", target_value: 80, direction: "higher_is_better", formula: "Mentorship effectiveness", applies_to_roles: "SE" },
    { id: 8, metric_key: "feedback_adoption", display_name: "Feedback Adoption", unit: "score", target_value: 80, direction: "higher_is_better", formula: "Rate of feedback incorporation", applies_to_roles: "ED" },
    { id: 9, metric_key: "capacity_utilization", display_name: "Capacity Utilization", unit: "percent", target_value: 82, direction: "band", formula: "projected / capacity × 100", applies_to_roles: "SE,ED,WR" },
  ],
  cp2_fact_pod_membership: [
    { id: 501, month_key: "2026-04", pod_id: 1, team_member_id: 101, role_in_pod: "SE", capacity_share: 0.3, notes: "split" },
    { id: 502, month_key: "2026-04", pod_id: 1, team_member_id: 102, role_in_pod: "ED", capacity_share: 1.0, notes: "" },
    { id: 503, month_key: "2026-04", pod_id: 1, team_member_id: 103, role_in_pod: "ED", capacity_share: 0.5, notes: "split with Pod 2" },
  ],
  cp2_fact_client_allocation: [
    { id: 701, month_key: "2026-04", pod_id: 1, client_id: 1, projected_articles: 25, projected_source: "sow", projected_articles_manual: null, notes: "" },
    { id: 702, month_key: "2026-04", pod_id: 1, client_id: 2, projected_articles: 5, projected_source: "operating_model", projected_articles_manual: null, notes: "" },
    { id: 703, month_key: "2026-04", pod_id: 1, client_id: 3, projected_articles: 8, projected_source: "manual", projected_articles_manual: 8, notes: "manual override per SE" },
  ],
  cp2_fact_member_leave: [
    { id: 901, team_member_id: 202, month_key: "2026-04", leave_share: 0.25, reason: "PTO", notes: "week 16" },
  ],
  cp2_fact_capacity_override: [
    { id: 1101, month_key: "2026-04", team_member_id: 203, pod_id: null, delta_articles: -2, reason: "onboarding ramp", created_by: "nina@graphitehq.com", created_at: "2026-03-28 11:14:02" },
  ],
  cp2_fact_actuals_weekly: [
    {
      id: 1301,
      week_key: "2026-W14",
      month_year_key: "2026-04",
      week_number: 1,
      week_date: "2026-03-30",
      pod_id: 1,
      client_id: 1,
      growth_team_pod: "growth-1",
      editorial_team_pod: "editorial-1",
      client_type: "SaaS",
      content_type: "blog",
      ratios: "2:1",
      delivered_articles: 6,
      goal_articles: 6,
      cb_delivered_today: 5,
      cb_projection: 6,
      cb_delivered_to_date: 5,
      cb_monthly_goal: 25,
      cb_pct_of_goal: "20%",
      cb_comments: "on pace",
      ad_revisions: 1,
      ad_delivered_today: 6,
      ad_projection: 6,
      ad_cb_backlog: 2,
      ad_delivered_to_date: 6,
      ad_monthly_goal: 25,
      ad_pct_of_goal: "24%",
      ad_comments: "",
      ingested_at: "2026-04-06 09:00:00",
    },
    {
      id: 1302,
      week_key: "2026-W15",
      month_year_key: "2026-04",
      week_number: 2,
      week_date: "2026-04-06",
      pod_id: 1,
      client_id: 1,
      growth_team_pod: "growth-1",
      editorial_team_pod: "editorial-1",
      client_type: "SaaS",
      content_type: "blog",
      ratios: "2:1",
      delivered_articles: 5,
      goal_articles: 6,
      cb_delivered_today: 6,
      cb_projection: 6,
      cb_delivered_to_date: 11,
      cb_monthly_goal: 25,
      cb_pct_of_goal: "44%",
      cb_comments: "",
      ad_revisions: 0,
      ad_delivered_today: 5,
      ad_projection: 6,
      ad_cb_backlog: 1,
      ad_delivered_to_date: 11,
      ad_monthly_goal: 25,
      ad_pct_of_goal: "44%",
      ad_comments: "1 in revision",
      ingested_at: "2026-04-13 09:00:00",
    },
  ],
  cp2_fact_kpi_score: [
    { id: 1501, month_key: "2026-04", team_member_id: 102, metric_id: 1, client_id: null, score: 87, target_snapshot: 85, source: "manual", entered_by: "nina@graphitehq.com", entered_at: "2026-04-30 17:02:11", notes: "aggregate" },
    { id: 1502, month_key: "2026-04", team_member_id: 102, metric_id: 1, client_id: 1, score: 88, target_snapshot: 85, source: "manual", entered_by: "nina@graphitehq.com", entered_at: "2026-04-30 17:02:11", notes: "per-client: College of BP" },
    { id: 1503, month_key: "2026-04", team_member_id: 102, metric_id: 3, client_id: null, score: 12, target_snapshot: 15, source: "notion", entered_by: null, entered_at: "2026-05-01 02:00:00", notes: "computed nightly" },
    { id: 1504, month_key: "2026-04", team_member_id: 102, metric_id: 6, client_id: null, score: 97, target_snapshot: 95, source: "ai_scan", entered_by: null, entered_at: "2026-05-01 02:00:00", notes: "from Writer AI 2.0" },
  ],
  cp2_fact_article: [
    {
      id: 2001,
      notion_case_id: "CASE-00123",
      client_id: 1,
      pod_id: 1,
      writer_id: 301,
      editor_id: 102,
      sr_editor_id: 101,
      month_key: "2026-04",
      title: "The Operator's Guide to Growth Loops",
      content_type: "blog",
      article_status: "PUBLISHED",
      cb_approved_date: "2026-04-02",
      delivered_date: "2026-04-11",
      published_date: "2026-04-15",
      turnaround_days: 9,
      revision_count: 0,
      had_second_review: true,
      published_url: "https://collegeofbp.com/growth-loops",
      notion_url: "https://notion.so/case-00123",
      status: "published",
    },
    {
      id: 2002,
      notion_case_id: "CASE-00124",
      client_id: 1,
      pod_id: 1,
      writer_id: 302,
      editor_id: 103,
      sr_editor_id: null,
      month_key: "2026-04",
      title: "Onboarding Benchmarks for Series A SaaS",
      content_type: "blog",
      article_status: "DELIVERED",
      cb_approved_date: "2026-04-05",
      delivered_date: "2026-04-22",
      published_date: null,
      turnaround_days: 17,
      revision_count: 2,
      had_second_review: false,
      published_url: null,
      notion_url: "https://notion.so/case-00124",
      status: "delivered",
    },
  ],
  cp2_fact_ai_scan: [
    {
      id: 3001,
      article_id: 2001,
      client_id: 1,
      pod_id: 1,
      month_key: "2026-04",
      topic_title: "The Operator's Guide to Growth Loops",
      topic_content: "Outline with 8 sections + CTA...",
      article_link: "https://collegeofbp.com/growth-loops",
      writer_name: "Chloe Davidson",
      editor_name: "Robert Trampe",
      scanned_at: "2026-04-11 14:22",
      date_processed: "2026-04-11",
      surfer_v1_score: 3.1,
      surfer_v2_score: 2.8,
      recommendation: "FULL_PASS",
      is_rewrite: false,
      is_flagged: false,
      manual_review_notes: "",
      action: "publish",
      notes: "",
    },
    {
      id: 3002,
      article_id: 2002,
      client_id: 1,
      pod_id: 1,
      month_key: "2026-04",
      topic_title: "Onboarding Benchmarks for Series A SaaS",
      topic_content: "Outline with 6 sections...",
      article_link: null,
      writer_name: "Drew Anand",
      editor_name: "Jimmy Bowes",
      scanned_at: "2026-04-22 10:02",
      date_processed: "2026-04-22",
      surfer_v1_score: 18.4,
      surfer_v2_score: 14.6,
      recommendation: "PARTIAL_PASS",
      is_rewrite: false,
      is_flagged: true,
      manual_review_notes: "Tone flagged as borderline; sections 3-4 rewritten",
      action: "revise",
      notes: "reviewed by ED",
    },
  ],
  cp2_fact_surfer_api_usage: [
    {
      id: 4500,
      year_month_key: "2026-03",
      start_date: "2026-03-01",
      end_date: "2026-03-31",
      pod_1: 68,
      pod_2: 74,
      pod_3: 52,
      pod_4: 0,
      pod_5: 0,
      auditioning_writers: 12,
      rewrites: 18,
      total_spent: 224,
      remaining_calls: 176,
    },
    {
      id: 4501,
      year_month_key: "2026-04",
      start_date: "2026-04-01",
      end_date: "2026-04-30",
      pod_1: 61,
      pod_2: 78,
      pod_3: 66,
      pod_4: 0,
      pod_5: 0,
      auditioning_writers: 9,
      rewrites: 14,
      total_spent: 228,
      remaining_calls: 172,
    },
  ],
  cp2_fact_delivery_monthly: [
    {
      id: 4001,
      month_key: "2026-04",
      client_id: 1,
      articles_sow_target: 25,
      articles_delivered: 24,
      articles_invoiced: 25,
      articles_paid: 23,
      articles_projected: 25,
      is_actual: true,
      variance: -1,
      content_briefs_delivered: 24,
      content_briefs_goal: 25,
      cumulative_delivered: 312,
      cumulative_invoiced: 310,
      source: "operating_model",
      notes: "",
    },
    {
      id: 4002,
      month_key: "2026-04",
      client_id: 2,
      articles_sow_target: 5,
      articles_delivered: 5,
      articles_invoiced: 5,
      articles_paid: 5,
      articles_projected: 5,
      is_actual: true,
      variance: 0,
      content_briefs_delivered: 5,
      content_briefs_goal: 5,
      cumulative_delivered: 50,
      cumulative_invoiced: 50,
      source: "operating_model",
      notes: "",
    },
  ],
  cp2_fact_production_history: [
    { id: 4801, client_id: 1, month_key: "2026-03", articles_actual: 22, articles_projected: 25, is_actual: true, source: "operating_model" },
    { id: 4802, client_id: 1, month_key: "2026-04", articles_actual: 24, articles_projected: 25, is_actual: true, source: "operating_model" },
    { id: 4803, client_id: 1, month_key: "2026-05", articles_actual: null, articles_projected: 25, is_actual: false, source: "operating_model" },
  ],
  cp2_fact_pipeline_snapshot: [
    {
      id: 5001,
      snapshot_date: "2026-04-15",
      client_id: 1,
      status: "ACTIVE",
      account_team_pod: "growth-1",
      client_type: "SaaS",
      content_type: "blog",
      topics_submitted: 420,
      topics_approved: 410,
      topics_pct_approved: "98%",
      cbs_submitted: 412,
      cbs_approved: 410,
      cbs_pct_approved: "99%",
      articles_sent: 398,
      articles_approved: 395,
      articles_difference: 3,
      articles_pct_approved: "99%",
      articles_delivered: 398,
      articles_published: 360,
      published_pct_live: "91%",
      articles_killed: 10,
      last_update: "2026-04-15",
      comments: "Q1 pipeline healthy",
    },
    {
      id: 5002,
      snapshot_date: "2026-04-15",
      client_id: 2,
      status: "ACTIVE",
      account_team_pod: "growth-2",
      client_type: "Enterprise",
      content_type: "thought-leadership",
      topics_submitted: 85,
      topics_approved: 80,
      topics_pct_approved: "94%",
      cbs_submitted: 80,
      cbs_approved: 80,
      cbs_pct_approved: "100%",
      articles_sent: 75,
      articles_approved: 73,
      articles_difference: 2,
      articles_pct_approved: "97%",
      articles_delivered: 75,
      articles_published: 55,
      published_pct_live: "73%",
      articles_killed: 2,
      last_update: "2026-04-15",
      comments: "",
    },
  ],
  cp2_dim_engagement_rule: [
    {
      id: 1,
      rule_number: 1,
      area: "workflow",
      rule_name: "CB approval before writer kickoff",
      description: "Writer cannot start drafting until CB is approved by SE.",
      owner: "SE",
      timing: "before_article_delivery",
      consequences: "Blocks article kickoff; escalate to AD after 48h.",
    },
    {
      id: 2,
      rule_number: 2,
      area: "quality",
      rule_name: "Second review on every new writer's first 5 articles",
      description: "SE performs a second-pass review on the first 5 deliveries from each new writer.",
      owner: "SE",
      timing: "per_article",
      consequences: "Tracked via cp2_fact_article.had_second_review.",
    },
  ],
  cp2_dim_model_assumption: [
    { id: 1, category: "capacity", key: "writer_ramp_up_months", value: "2", description: "New writers hit full capacity after N months." },
    { id: 2, category: "pacing", key: "on_track_tolerance_pct", value: "10", description: "Allowed ±% deviation from template before flagging AT_RISK." },
    { id: 3, category: "kpi", key: "ai_compliance_target_pct", value: "95", description: "Global AI compliance target (FULL_PASS rate)." },
  ],
};
